services:
      ui.controller.survey_controller:
            class: App\UI\Controller\MakeSurveyController
            arguments:
                - '@tactician.commandbus'
                - '@infrastructure.doctrine.survey_view'
                - '@infrastructure.doctrine.question_view'
                - '@infrastructure.doctrine.offered_answer_view'
                - '@infrastructure.doctrine.answer_view'

      ui.controller.question_controller:
            class: App\UI\Controller\MakeQuestionController
            arguments:
                - '@tactician.commandbus'
                - '@infrastructure.doctrine.survey_view'
                - '@infrastructure.doctrine.question_view'
                - '@infrastructure.doctrine.offered_answer_view'
          #  tags: ['controller.service_arguments']
      ui.controller.offered_answer_controller:
            class: App\UI\Controller\MakeOfferedAnswerController
            arguments:
                - '@tactician.commandbus'
                - '@infrastructure.doctrine.question_view'
                - '@infrastructure.doctrine.offered_answer_view'
          #  tags: ['controller.service_arguments']
      ui.controller.control_panel_controller:
          class: App\UI\Controller\ControlPanelController
          calls:
              - [setContainer, ['@service_container']]

      ui.controller.show_survey_controller:
          class: App\UI\Controller\ShowSurveyController
          arguments:
              - '@tactician.commandbus'
              - '@infrastructure.doctrine.survey_view'
              - '@infrastructure.doctrine.question_view'
              - '@infrastructure.doctrine.offered_answer_view'

      ui.controller.main_page_controller:
          class: App\UI\Controller\MainPageController
          arguments:
              - '@infrastructure.doctrine.survey_view'
          calls:
              - [setContainer, ['@service_container']]

      ui.controller.fill_survey_controller:
          class: App\UI\Controller\FillSurveyController
          arguments:
              - '@tactician.commandbus'
              - '@infrastructure.doctrine.rebate_code_view'
          calls:
              - [setContainer, ['@service_container']]

      ui.controller.show_table_answers_controller:
          class: App\UI\Controller\ShowTableAnswersController
          arguments:
                - '@infrastructure.doctrine.answer_view'
                - '@infrastructure.doctrine.question_view'
                - '@infrastructure.doctrine.survey_view'
          calls:
              - [setContainer, ['@service_container']]

      ui.controller.login_controller:
          class: App\UI\Controller\LoginController
          arguments:
                - '@infrastructure.doctrine.user_view'
          calls:
              - [setContainer, ['@service_container']]

      ui.controller.users_controller:
          class: App\UI\Controller\UsersController
          arguments:
                - '@tactician.commandbus'
          calls:
              - [setContainer, ['@service_container']]

      ui.controller.generate_code_controller:
          class: App\UI\Controller\GenerateCodeController
          arguments:
                - '@tactician.commandbus'
          calls:
              - [setContainer, ['@service_container']]

      ui.form.generate_survey_type:
          class: App\UI\Form\GenerateSurveyType
          arguments:
              - '@infrastructure.doctrine.survey_view'
              - '@infrastructure.doctrine.question_view'
              - '@infrastructure.doctrine.offered_answer_view'