services:

    ui.controller.survey_controller:
          class: App\UI\Controller\AdminSide\SurveyController
          arguments:
              - '@tactician.commandbus'
              - '@infrastructure.doctrine.survey_view'
              - '@infrastructure.doctrine.question_view'
              - '@infrastructure.doctrine.offered_answer_view'
              - '@infrastructure.doctrine.answer_view'
              - '@session'
          tags: ['controller.service_arguments']


    ui.controller.question_controller:
          class: App\UI\Controller\AdminSide\QuestionController
          arguments:
              - '@tactician.commandbus'
              - '@infrastructure.doctrine.survey_view'
              - '@infrastructure.doctrine.question_view'
              - '@infrastructure.doctrine.offered_answer_view'
              - '@session'
          tags: ['controller.service_arguments']

    ui.controller.offered_answer_controller:
          class: App\UI\Controller\AdminSide\OfferedAnswerController
          arguments:
              - '@tactician.commandbus'
              - '@infrastructure.doctrine.question_view'
              - '@infrastructure.doctrine.offered_answer_view'
              - '@session'
          tags: ['controller.service_arguments']

    ui.controller.control_panel_controller:
        class: App\UI\Controller\AdminSide\ControlPanelController
        arguments:
              - '@session'
        calls:
            - [setContainer, ['@service_container']]
        tags: ['controller.service_arguments']

    ui.controller.show_survey_controller:
        class: App\UI\Controller\AdminSide\ShowSurveyController
        arguments:
            - '@tactician.commandbus'
            - '@infrastructure.doctrine.survey_view'
            - '@infrastructure.doctrine.question_view'
            - '@infrastructure.doctrine.offered_answer_view'
            - '@session'
        tags: ['controller.service_arguments']

    ui.controller.main_page_controller:
        class: App\UI\Controller\UserSide\MainPageController
        arguments:
            - '@infrastructure.doctrine.survey_view'
        calls:
            - [setContainer, ['@service_container']]
        tags: ['controller.service_arguments']

    ui.controller.fill_survey_controller:
        class: App\UI\Controller\UserSide\FillSurveyController
        arguments:
            - '@tactician.commandbus'
            - '@infrastructure.doctrine.rebate_code_view'
        calls:
            - [setContainer, ['@service_container']]
        tags: ['controller.service_arguments']

    ui.controller.show_table_answers_controller:
        class: App\UI\Controller\AdminSide\ShowTableAnswersController
        arguments:
              - '@infrastructure.doctrine.answer_view'
              - '@infrastructure.doctrine.question_view'
              - '@infrastructure.doctrine.survey_view'
              - '@session'
        calls:
            - [setContainer, ['@service_container']]
        tags: ['controller.service_arguments']

    ui.controller.login_controller:
        class: App\UI\Controller\AdminSide\LoginController
        arguments:
              - '@infrastructure.doctrine.user_view'
              - '@session'
        calls:
            - [setContainer, ['@service_container']]
        tags: ['controller.service_arguments']

    ui.controller.users_controller:
        class: App\UI\Controller\AdminSide\UsersController
        arguments:
              - '@tactician.commandbus'
        calls:
            - [setContainer, ['@service_container']]
        tags: ['controller.service_arguments']

    ui.controller.generate_code_controller:
        class: App\UI\Controller\UserSide\GenerateCodeController
        arguments:
              - '@tactician.commandbus'
        calls:
            - [setContainer, ['@service_container']]
        tags: ['controller.service_arguments']

    ui.form.generate_survey_type:
        class: App\UI\Form\UserSide\GenerateSurveyType
        arguments:
            - '@infrastructure.doctrine.survey_view'
            - '@infrastructure.doctrine.question_view'
            - '@infrastructure.doctrine.offered_answer_view'
        tags: [form.type]