# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    #app.application.create_survey_handler:
    #   class:  App\Application\Command\CreateNewSurveyHandler
    #      arguments:
    #        - '@app.domain.repository.survey_repository'
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Domain,Application,Infrastructure,UI,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    #App\UI\Controller\:
        #resource: '../src/UI/Controller'
        #tags: ['controller.service_arguments']
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    survey.repository:
          class: App\Infrastructure\Domain\DbalSurveyRepository
          arguments:
              - '@doctrine'

    question.repository:
          class: App\Infrastructure\Domain\DbalQuestionRepository
          arguments:
              - '@doctrine'

    offered_answer.repository:
          class: App\Infrastructure\Domain\DbalOfferedAnswerRepository
          arguments:
              - '@doctrine'
    answer.repository:
        class: App\Infrastructure\Domain\DbalAnswerRepository
        arguments:
              - '@doctrine'


    ui.controller.survey_controller:
          class: App\UI\Controller\MakeSurveyController
          arguments:
              - '@tactician.commandbus'
              - '@infrastructure.doctrine.survey_view'
              - '@infrastructure.doctrine.question_view'
              - '@infrastructure.doctrine.offered_answer_view'

    ui.controller.question_controller:
          class: App\UI\Controller\MakeQuestionController
          arguments:
              - '@tactician.commandbus'
              - '@infrastructure.doctrine.survey_view'
              - '@infrastructure.doctrine.question_view'
        #  tags: ['controller.service_arguments']
    ui.controller.offered_answer_controller:
          class: App\UI\Controller\MakeOfferedAnswerController
          arguments:
              - '@tactician.commandbus'
              - '@infrastructure.doctrine.question_view'
              - '@infrastructure.doctrine.offered_answer_view'
        #  tags: ['controller.service_arguments']
    ui.controller.control_panel_controller:
        class: App\UI\Controller\ControlPanelController
        calls:
            - [setContainer, ['@service_container']]

    ui.controller.show_survey_controller:
        class: App\UI\Controller\ShowSurveyController
        arguments:
            - '@tactician.commandbus'
            - '@infrastructure.doctrine.survey_view'
            - '@infrastructure.doctrine.question_view'
            - '@infrastructure.doctrine.offered_answer_view'

    ui.controller.main_page_controller:
        class: App\UI\Controller\MainPageController
        arguments:
            - '@infrastructure.doctrine.survey_view'
        calls:
            - [setContainer, ['@service_container']]
    ui.controller.fill_survey_controller:
        class: App\UI\Controller\FillSurveyController
        arguments:
            - '@tactician.commandbus'
        calls:
            - [setContainer, ['@service_container']]


    application.command.create_survey:
          class: App\Application\Command\Survey\CreateNewSurveyHandler
          arguments:
              - '@survey.repository'
          tags:
              - { name: tactician.handler, command: App\Application\Command\Survey\CreateNewSurveyCommand }

    application.command.create_question:
          class: App\Application\Command\Question\CreateNewQuestionHandler
          arguments:
              - '@question.repository'
          tags:
              - { name: tactician.handler, command: App\Application\Command\Question\CreateNewQuestionCommand }

    application.command.create_offered_answer:
          class: App\Application\Command\OfferedAnswer\CreateNewOfferedAnswerHandler
          arguments:
              - '@offered_answer.repository'
          tags:
              - { name: tactician.handler, command: App\Application\Command\OfferedAnswer\CreateNewOfferedAnswerCommand }

    application.command.offered_answer.delete_offered_answer:
        class: App\Application\Command\OfferedAnswer\DeleteOfferedAnswerHandler
        arguments:
            - '@offered_answer.repository'
        tags:
            - { name: tactician.handler, command: App\Application\Command\OfferedAnswer\DeleteOfferedAnswerCommand }

    application.command.question.delete_question:
        class: App\Application\Command\Question\DeleteQuestionHandler
        arguments:
            - '@question.repository'
        tags:
            - { name: tactician.handler, command: App\Application\Command\Question\DeleteQuestionCommand }

    application.command.survey.delete_survey:
        class: App\Application\Command\Survey\DeleteSurveyHandler
        arguments:
            - '@survey.repository'
        tags:
            - { name: tactician.handler, command: App\Application\Command\Survey\DeleteSurveyCommand }



    infrastructure.doctrine.survey_view:
          class: App\Infrastructure\Doctrine\DbalSurveyView
          arguments: ['@Doctrine\DBAL\Driver\Connection']

    infrastructure.doctrine.question_view:
          class : App\Infrastructure\Doctrine\DbalQuestionView
          arguments: ['@Doctrine\DBAL\Driver\Connection']

    infrastructure.doctrine.offered_answer_view:
          class : App\Infrastructure\Doctrine\DbalOfferedAnswerView
          arguments: ['@Doctrine\DBAL\Driver\Connection']